### ISSUE TITLE
Dispatcher is not caching the updated content when using with SDI

### ISSUE THREAD

**Issue by kumesh65** [wttech/Sling-Dynamic-Include#28]
Hi,
I am using SDI to cache the experience fragment for header and footer, but I am facing one issue with the content that is,
when I publish the content for the first time it gets cached on the dispatcher but when I updated the same content, it got reflects properly on publisher but on dispatcher it is still showing the old content, that was cached for the first time even after clearing the dispatcher cache.
But when I disable the SDI on publisher it works fine for me.
I ma using TTL for one year and apache ssi as configuration in the config for sdi.
Can anyone provide some insight on it what needs to be done to change this expected behaviour of SDI and dispatcher.
Thanks
Umesh Thakur

**Comment by benpeter** [comment]
Hi Umesh,

you can either set the statfile level on dispatcher to match the root of your website (so that any chance on or below the homepage invalidates the entire site on dispatcher) or use the SSI feature of SDI so that the pages are pieced together on the web server / dispatcher instead of on the publish (which leads to inconsistent caching on the dispatcher).

Cheers
Ben

**Comment by kumesh65** [comment]
Hi Ben,
We are operating an e-commerce heave traffic site so can not invalidate the entire site's cache so is there any option I have to remove  only those cache that was being cached by SDI. This is the only culprit, that is causing the issue. If I disable SDI it works fine for me.
Thanks
Umesh Thakur

**Comment by devzbysiu** [comment]
This project has been moved to https://github.com/apache/sling-org-apache-sling-dynamic-include and it's not maintained here. Closing
